### ISSUE TITLE
problem with theme inheritance

### ISSUE THREAD

**Issue by popebear** [hibbitts-design/grav-theme-antimatter-open-publishing#5]
Hi Guys
I love this theme but wanted to extend it using inheritance as described in this document. https://learn.getgrav.org/themes/customization

I believe that mytheme.php would need to be:
`<?php
namespace Grav\Theme;

class Mytheme extends antimatter-open-publishing
{
   // Some new methods, properties etc.
}
?>`

However, when I try this I get the error
"unexpected character -" (referring to the hyphens in the theme name)

Is this a bug or am I approaching it the wrong way?

**Comment by paulhibbitts** [comment]
Hi @popebear , glad you are fining the theme useful! As you have discovered, hyphens are not supported for class names. Try this in your mytheme.php:

```
<?php
namespace Grav\Theme;

use Grav\Common\Theme;

class myTheme extends Theme
{
}
?>
```

And then this in your mytheme.yaml file try this:

```
streams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
       - user/themes/mytheme
       - user/themes/antimatter-open-publishing
       - user/themes/antimatter
```
You could also download an earlier release of the Open Publishing Skeleton (it now has Quark as the default theme) to see a working example of this: https://github.com/hibbitts-design/grav-skeleton-open-publishing-space/releases/download/v1.1.6/grav-skeleton-open-publishing-space-site.zip

Let me know if the above works for you.
